### PR TITLE
Moves images & renames for consistency

### PR DESCRIPTION
**Pull request by ElizabethN**
This PR moves the images folders for these 2 metrics models to be consistent with other metrics models:
 - Project Engagement
 - Community Activity

This PR also fixes broken images links for these metrics models and renames the Project Engagement model to be more consistent with the naming of other metrics models.

Note to website team that we will need to update the path to these metrics on the site.

Signed-off-by: Elizabeth Barron <elizabeth@naramore.net>

### CODE REVIEW

**Comment by ElizabethN** [comment]
@eyehwan we noticed some broken images on the website in our metrics models so this is an attempt to fix that and also bring consistency to the folder structure & naming. Thanks for reviewing for me - I dont often move things around and rename things :smile:

**Comment by ElizabethN** [comment]
@germonprez yep! I think these still need to be fixed. Thank you!

**Comment by ElizabethN** [comment]
@germonprez if it's better, I can break these into smaller PRs. The changes are simple path changes, but it does change a lot of files, and I see there are some merge conflicts now. Feel free to close this and I'll tackle them one at a time. :blush:

**Comment by germonprez** [comment]
All good. I'll merge this!

**Comment by ElizabethN** [comment]
I'm going to close this and break this into smaller PRs

**Pull request closed without merging**
