### PR TITLE
Starter Project Health Metrics Model

### PR DESCRIPTION
**Pull request by geekygirldawn**
Here's the PR for the new Starter Project Health Metrics model based on the [Google Doc](https://docs.google.com/document/d/1jBBKIEYaeI61LKjYHTnCh3a4Ih7zq6LuZA_arBmr0_M/edit) and as described in Issue #69

### CODE REVIEW

**Review by tsadler1988 — COMMENTED** [review]
From a beginner's point of view this is a great model!

- Added a couple of (perhaps pedantic?) suggestions
- Also raised a [PR to remove line breaks](https://github.com/geekygirldawn/wg-metrics-models/pull/1), as in my experience MD files are easier to maintain this way

**Review by eyehwan — APPROVED** [review]
Looks good to me!

**Comment by geekygirldawn** [comment]
@germonprez @klumb @ElizabethN - do we have a preference for adding / not adding line breaks in markdown files? I usually try to add a line break to end up with lines at a max of ~80 chars? As a vim user, this makes editing the files a lot easier for me, and it's standard coding practice, but one can argue that markdown isn't really "code", so I'm not sure if we care about this either way. @tsadler1988 created a PR to remove all of the line breaks, but I wanted to see if we have a preference as a project before deciding whether to merge it. 

Does it make a difference either way when the markdown files are displayed in Wordpress? Do we have a preference for this as a project?

**Review by germonprez — APPROVED** [review]
Thanks everyone! I'm going to merge this.

**Pull request merged**
