### PR TITLE
Fernanda proposal

### PR DESCRIPTION
**Pull request by sgoggins**

### CODE REVIEW

**Comment by sgoggins** [comment]
@eyehwan : I think this PR is a useful, high level "index" (there must be a better word!) of the conversion rate metric.

**Comment by sgoggins** [comment]
@eyehwan : I invited your GitHub user to the CHAOSS Org so I can note you on this PR in the metadata.

**Comment by eyehwan** [comment]
@sgoggins Hi Sean, is it a GSOC proposal?

**Comment by germonprez** [comment]
@sgoggins is this something to be merged? The title isn't great so it's hard to tell if this is something to include or just some ideas. If it is ideas, I suggest that we move it out of a PR and capture it somewhere else.

**Pull request closed without merging**
