### PR TITLE
Delete focus-areas directory

### PR DESCRIPTION
**Pull request by germonprez**
Signed-off-by: Matt Germonprez germonprez@gmail.com

I would like to delete this directory. As we are now reworking the metrics models repository design a bit, this directory is no longer needed. There is no material that is being deleted with the removal of this directory, only the empty directory itself.

### CODE REVIEW

**Comment by eyehwan** [comment]
There is one issuse-handling MM in development folder , that is deployed by me long time ago. But I think it is ready to be removed together with focus-areas, I will refactor in the metrics-model-libs folder.

**Review by eyehwan — APPROVED** [review]

**Comment by germonprez** [comment]
Thanks for catching that @eyehwan That would be great if you could refactor it.

**Comment by eyehwan** [comment]
I didn't  have access to help merge. So I guess @sgoggins or youself could merge the code directly.

**Comment by germonprez** [comment]
@eyehwan I have added you as a maintainer on the repo :)

**Comment by eyehwan** [comment]
Thanks! Just merge it.

**Pull request merged**
